name: Dynamic references in workflow files for different environments in your Mule application.

on:
  push:
    branches:
      - main
      - dev
      - uat
      - qa
env: 
  SECURE_KEY: ${{secrets.SECURE_KEY}}
jobs:
    # Job to deploy the application on anypoint platform's Runtime manager
    
  call-cicd-workflow: # call cicd main flow
    uses: uservaj/mc-cicd-org-template/.github/workflows/main.yml@main
    with:
      environment: ${{ github.ref_name }}
      secure_key: ${{ env.SECURE_KEY }}
    secrets: inherit
