name: Reference to workflow files necessary to handle deployment of Mule Applciation

on:
  push:
    branches: ["main", "dev", "uat", "qa"]
  pull_request:
    branches: ["main", "dev", "uat", "qa"]

jobs:
  Mule-Deploy:
    uses: uservaj/mc-sample-mule-api/.github/workflows/deploy-dev.yml@main
    secrets: inherit
